sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ricardojmclaudio/docker-react -f Dockerfile.dev .

script:
  - docker run ricardojmclaudio/docker-react npm run test -- --coverage